In [23]:
import pandas as pd
import numpy as np

#### loading the data

In [ ]:
df = pd.read_csv(r"data\Sales_April_2019.csv")

#### looking into the dataset

In [25]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,4/19/2019 8:46,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,4/7/2019 22:30,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600.00,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176560,Wired Headphones,1,11.99,4/12/2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176561,Wired Headphones,1,11.99,4/30/2019 9:27,"333 8th St, Los Angeles, CA 90001"

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18267 entries, 0 to 18266
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          18267 non-null  int64
 1   Product           18267 non-null  object
 2   Quantity Ordered  18267 non-null  int64
 3   Price Each        18267 non-null  float64
 4   Order Date        18267 non-null  object
 5   Purchase Address  18267 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 856.4+ KB

In [27]:
df.nunique()

Order ID            17537
Product                19
Quantity Ordered        7
Price Each             17
Order Date          13583
Purchase Address    17119
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

#### fixing the column names

In [29]:
df.columns = df.columns.str.lower().str.replace(' ','_')
df.columns

Index(['order_id', 'product', 'quantity_ordered', 'price_each', 'order_date',
       'purchase_address'],
      dtype='object')

#### fixing the data types

In [30]:
df['order_date'] = pd.to_datetime(df['order_date'],format='mixed')

In [31]:
df['price_each'] = df['price_each'].astype(float)
df['quantity_ordered'] = df['quantity_ordered'].astype(int)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18267 entries, 0 to 18266
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          18267 non-null  int64
 1   product           18267 non-null  object
 2   quantity_ordered  18267 non-null  int64
 3   price_each        18267 non-null  float64
 4   order_date        18267 non-null  datetime64[ns]
 5   purchase_address  18267 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(2)
memory usage: 856.4+ KB

#### calculating some columns

In [33]:
df['city'] = df['purchase_address'].str.split(',').str[1].str.strip()

In [34]:
df['state'] = (df['purchase_address'].str.split(',').str[2].str.strip().str.split().str[0])

In [35]:
df['total_amount'] = df['quantity_ordered'] * df['price_each']

In [36]:
df['day_of_week'] = df['order_date'].dt.day_name()

In [37]:
df['hour'] = df['order_date'].dt.hour

In [38]:
df['order_day'] = df['order_date'].dt.date

#### final look

In [39]:
df.head()

,order_id,product,quantity_ordered,price_each,order_date,purchase_address,city,state,total_amount,day_of_week,hour,order_day
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001",Dallas,TX,23.90,Friday,8,2019-04-19
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215",Boston,MA,99.99,Sunday,22,2019-04-07
2,176560,Google Phone,1,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,CA,600.00,Friday,14,2019-04-12
3,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",Los Angeles,CA,11.99,Friday,14,2019-04-12
4,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001",Los Angeles,CA,11.99,Tuesday,9,2019-04-30

In [40]:
df['city'].unique()

array(['Dallas', 'Boston', 'Los Angeles', 'San Francisco', 'Seattle',
       'Atlanta', 'New York City', 'Portland', 'Austin'], dtype=object)

In [41]:
df['state'].unique()

array(['TX', 'MA', 'CA', 'WA', 'GA', 'NY', 'OR', 'ME'], dtype=object)

In [42]:
df.describe()

,order_id,quantity_ordered,price_each,order_date,total_amount,hour
count,18267.000000,18267.000000,18267.000000,18267,18267.000000,18267.000000
mean,185330.420595,1.124760,184.573645,2019-04-16 03:15:17.135818752,185.832750,14.338589
min,176558.000000,1.000000,2.990000,2019-04-01 03:09:00,2.990000,0.000000
25%,180953.500000,1.000000,11.950000,2019-04-08 17:03:00,11.950000,11.000000
50%,185332.000000,1.000000,14.950000,2019-04-16 00:47:00,14.950000,15.000000
75%,189707.500000,1.000000,150.000000,2019-04-23 15:19:30,150.000000,19.000000
max,194094.000000,7.000000,1700.000000,2019-05-01 04:25:00,3400.000000,23.000000
std,5061.670698,0.436651,331.069060,NaN,332.381465,5.429847

In [43]:
df.isnull().sum()

order_id            0
product             0
quantity_ordered    0
price_each          0
order_date          0
purchase_address    0
city                0
state               0
total_amount        0
day_of_week         0
hour                0
order_day           0
dtype: int64

#### exporting the clean dataset

In [ ]:
df.to_csv(r"data\clean_sales.csv",index=False)